version: '3.7'

services:
  chrome:
    image: selenium/node-chrome:4.4.0-20220812
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"

  db:
    image: postgres:12.5
    ports:
     - "5432:5432"
    restart: always
    volumes:
     - production_db_volume:/var/lib/postgresql/data/
    env_file:
     - .live.env

  app:
    restart: always
    command : bash -c "
                      (python3 manage.py makemigrations) &&
                      (python3 manage.py migrate) &&
                      (python3 manage.py runserver 0.0.0.0:8000 &) &&
                      (celery -A aarons_kit worker -B)"
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .live.env
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    build:
      context: ./proxy
    volumes:
      - production_static_data:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  selenium-hub:
    image: selenium/hub:4.4.0-20220812
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

volumes:
  production_static_data:
  production_db_volume: