# Generated by Django 4.0.3 on 2022-05-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Surname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('JournalID', models.IntegerField(primary_key=True, serialize=False)),
                ('JournalName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('PublisherName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('SubCategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('SubCategory', models.CharField(max_length=100)),
                ('CategoryID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='aarons_kit_api.categories')),
            ],
        ),
        migrations.CreateModel(
            name='JournalSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JournalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='aarons_kit_api.journals')),
                ('SubCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='aarons_kit_api.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('IssueID', models.IntegerField(primary_key=True, serialize=False)),
                ('IssueName', models.CharField(max_length=100)),
                ('Year', models.IntegerField(default=0)),
                ('Volume', models.IntegerField(default=0)),
                ('Number', models.IntegerField(default=0)),
                ('JournalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarons_kit_api.journals')),
                ('PublisherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarons_kit_api.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('ArticleID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500)),
                ('DOI', models.CharField(max_length=200)),
                ('Abstract', models.CharField(max_length=10000)),
                ('References', models.CharField(max_length=10000)),
                ('URL', models.CharField(max_length=1000)),
                ('Scraped', models.BooleanField(default=False)),
                ('IssueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aarons_kit_api.issues')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='aarons_kit_api.articles')),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aarons_kit_api.authors')),
            ],
        ),
        migrations.AddConstraint(
            model_name='journalsubcategories',
            constraint=models.UniqueConstraint(fields=('JournalID', 'SubCategoryID'), name='JournalSubCategory'),
        ),
        migrations.AddConstraint(
            model_name='articleauthors',
            constraint=models.UniqueConstraint(fields=('AuthorID', 'ArticleID'), name='ArticleAuthor'),
        ),
    ]
