# Generated by Django 4.0.3 on 2022-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarons_kit_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
