# Generated by Django 4.0.3 on 2022-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarons_kit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='ArticleID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authors',
            name='AuthorID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='CategoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issues',
            name='IssueID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journals',
            name='JournalID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='SubCategoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
