<<<<<<< HEAD:aarons_kit_api/migrations/0001_initial.py
# Generated by Django 4.0.3 on 2022-08-23 15:23
=======
# Generated by Django 4.0.4 on 2022-08-24 11:08
>>>>>>> d25ed0b8307e348b41334bfcc1412ecddd72c990:api/migrations/0001_initial.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.AutoField(primary_key=True, serialize=False)),
                ('authorName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journalID', models.AutoField(primary_key=True, serialize=False)),
                ('issn', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=500, null=True, unique=True)),
                ('altISSN', models.CharField(max_length=50)),
                ('journalName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issueID', models.AutoField(primary_key=True, serialize=False)),
                ('issueJstorID', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500, null=True, unique=True)),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('url', models.CharField(max_length=1000)),
                ('articleJstorID', models.CharField(max_length=50)),
                ('authors', models.ManyToManyField(to='api.author')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.issue')),
            ],
        ),
    ]
