# Generated by Django 4.0.4 on 2022-08-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleJstorID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueJstorID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='altISSN',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journalName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
