# Generated by Django 4.0.4 on 2022-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolume',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeIssue',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeIssueScrapped',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeScrapped',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='numberOfIssues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='numberOfIssuesScrapped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journalName',
            field=models.CharField(max_length=500),
        ),
    ]
