# Generated by Django 4.0.4 on 2022-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_article_articlejstorid_alter_article_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='lastVolume',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeIssue',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeIssueScraped',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastVolumeScraped',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='numberOfIssues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='numberOfIssuesScraped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journalName',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
