# Generated by Django 4.0.4 on 2022-09-06 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue_url_journal_lastvolume_journal_lastvolumeissue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='numberOfIssuesScrapped',
            new_name='numberOfIssuesScraped',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolume',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeIssue',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeIssueScrapped',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeScrapped',
        ),
        migrations.AddField(
            model_name='journal',
            name='lastIssueDate',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastIssueDateScraped',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
