# Generated by Django 4.0.4 on 2022-09-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_journal_lastvolume_journal_lastvolumeissue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='bucketURL',
        ),
    ]
