# Generated by Django 4.0.4 on 2022-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_url_article_bucketurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bucketURL',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
