# Generated by Django 4.0.4 on 2022-09-07 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_article_bucketurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='lastVolume',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeIssue',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeIssueScraped',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='lastVolumeScraped',
        ),
        migrations.AddField(
            model_name='article',
            name='articleURL',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastIssueDate',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='journal',
            name='lastIssueDateScraped',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='journal',
            name='url',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueJstorID',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='altISSN',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
