# Generated by Django 4.0.4 on 2022-09-13 14:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_journal_lastvolume_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='article_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.GinIndex(fields=['authorName'], name='author_authorName_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['journalName'], name='journal_journalName_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
