# Generated by Django 4.0.4 on 2023-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_alter_article_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
